const MOVIES_GET_REQUEST = 'MOVIES_GET_REQUEST';
const MOVIES_GET_SUCCESS = 'MOVIES_GET_SUCCESS';
const MOVIES_GET_FAILURE = 'MOVIES_GET_FAILURE';

const MOVIES_POST_REQUEST = 'MOVIES_POST_REQUEST';
const MOVIES_POST_SUCCESS = 'MOVIES_POST_SUCCESS';
const MOVIES_POST_FAILURE = 'MOVIES_POST_FAILURE';

const MOVIE_GET_REQUEST = 'MOVIE_GET_REQUEST';
const MOVIE_GET_SUCCESS = 'MOVIE_GET_SUCCESS';
const MOVIE_GET_FAILURE = 'MOVIE_GET_FAILURE';

const MOVIE_DELETE_REQUEST = 'MOVIE_DELETE_REQUEST';
const MOVIE_DELETE_SUCCESS = 'MOVIE_DELETE_SUCCESS';
const MOVIE_DELETE_FAILURE = 'MOVIE_DELETE_FAILURE';

const MOVIE_PUT_REQUEST = 'MOVIE_PUT_REQUEST';
const MOVIE_PUT_SUCCESS = 'MOVIE_PUT_SUCCESS';
const MOVIE_PUT_FAILURE = 'MOVIE_PUT_FAILURE';

export const types = {
    MOVIES_GET_REQUEST,
    MOVIES_GET_SUCCESS,
    MOVIES_GET_FAILURE,

    MOVIES_POST_REQUEST,
    MOVIES_POST_SUCCESS,
    MOVIES_POST_FAILURE,

    MOVIE_GET_REQUEST,
    MOVIE_GET_SUCCESS,
    MOVIE_GET_FAILURE,

    MOVIE_DELETE_REQUEST,
    MOVIE_DELETE_SUCCESS,
    MOVIE_DELETE_FAILURE,

    MOVIE_PUT_REQUEST,
    MOVIE_PUT_SUCCESS,
    MOVIE_PUT_FAILURE

}