const PERSONS_GET_REQUEST = 'PERSONS_GET_REQUEST';
const PERSONS_GET_SUCCESS = 'PERSONS_GET_SUCCESS';
const PERSONS_GET_FAILURE = 'PERSONS_GET_FAILURE';

const PERSONS_POST_REQUEST = 'PERSONS_POST_REQUEST';
const PERSONS_POST_SUCCESS = 'PERSONS_POST_SUCCESS';
const PERSONS_POST_FAILURE = 'PERSONS_POST_FAILURE';

const PERSON_GET_REQUEST = 'PERSON_GET_REQUEST';
const PERSON_GET_SUCCESS = 'PERSON_GET_SUCCESS';
const PERSON_GET_FAILURE = 'PERSON_GET_FAILURE';

const PERSON_DELETE_REQUEST = 'PERSON_DELETE_REQUEST';
const PERSON_DELETE_SUCCESS = 'PERSON_DELETE_SUCCESS';
const PERSON_DELETE_FAILURE = 'PERSON_DELETE_FAILURE';

const PERSON_PUT_REQUEST = 'PERSON_PUT_REQUEST';
const PERSON_PUT_SUCCESS = 'PERSON_PUT_SUCCESS';
const PERSON_PUT_FAILURE = 'PRESON_PUT_FAILURE';

export const types = {
    PERSONS_GET_REQUEST,
    PERSONS_GET_SUCCESS,
    PERSONS_GET_FAILURE,

    PERSONS_POST_REQUEST,
    PERSONS_POST_SUCCESS,
    PERSONS_POST_FAILURE,
    
    PERSON_GET_REQUEST,
    PERSON_GET_SUCCESS,
    PERSON_GET_FAILURE,

    PERSON_DELETE_REQUEST,
    PERSON_DELETE_SUCCESS,
    PERSON_DELETE_FAILURE,
    
    PERSON_PUT_REQUEST,
    PERSON_PUT_SUCCESS,
    PERSON_PUT_FAILURE,
}